name: Build, Test, and Release App

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ] # e.g. v1.0.0
  pull_request:
    branches: [ main ]

permissions:
  contents: write   # Gives the publish token write access

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # Adjust for your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      # Only publish when pushing a version tag
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet publish WpfTreeViewTest/WpfTreeViewTest.csproj -c Release -r win-x64 --self-contained false -o publish

      - name: Decode signing certificate  # Needs to be base64 encoded and uploaded as a secret
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.WINDOWS_CERT_BASE64 }}" > cert.base64
          certutil -decode cert.base64 cert.pfx
        shell: pwsh

      - name: Sign executables
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $certPath = "cert.pfx"
          $password = "${{ secrets.WINDOWS_CERT_PASSWORD }}"
          $signtool = (Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe |
                      Where-Object { $_.FullName -match "\\x64\\" } |
                      Sort-Object FullName -Descending |
                      Select-Object -First 1).FullName
          
          if (-not (Test-Path $signtool)) {
            throw "signtool.exe (x64) not found!"
          }
          
          Write-Host "Using signtool at $signtool"
          
          $files = Get-ChildItem publish -Include *.exe,*.msi -Recurse
          foreach ($f in $files) {
            & $signtool sign `
              /f $certPath /p $password /fd SHA256 /tr http://timestamp.digicert.com /td SHA256 `
              "$($f.FullName)"
          }
        shell: pwsh

      - name: Zip published output
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $tag = "${{ github.ref_name }}"
          Compress-Archive -Path publish\* -DestinationPath "WpfTreeView-$tag.zip"

      - name: Upload Build Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: WpfTreeView   # Adjust for project name
          path: WpfTreeView-${{ github.ref_name }}.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: WpfTreeView-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}