name: Build, Test, and Release App

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ] # e.g. v1.0.0
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # Adjust for your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      # Only publish when pushing a version tag
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet publish WpfTreeViewTest/WpfTreeViewTest.csproj -c Release -r win-x64 --self-contained true -o publish

      - name: Upload Build Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: WpfApp
          path: publish/**

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: publish/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}